const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

async function main() {
    // Clear existing products
    await prisma.product.deleteMany({})
    console.log('🗑️  Cleared existing products')

    // Use the same images as mockData.ts - all from /img/ folder
    const products = [
        { name: "Sonic Wave EarPods", description: "Premium wireless earbuds with active noise cancellation", fullDescription: "Experience audio like never before with Sonic Wave EarPods. These premium wireless earbuds feature advanced active noise cancellation, spatial audio technology, and up to 30 hours of battery life with the charging case.", features: "Active Noise Cancellation\nSpatial Audio\n30-hour battery\nIPX4 Water resistant\nTouch controls\nQuick charge", specs: '{"Driver": "11mm", "Frequency": "20Hz-20kHz", "Battery": "6h+24h", "Charging": "USB-C"}', price: 35000, image: "/img/Sonic Wave EarPods.jpg", category: "Earphones", stock: 80, rating: 4.8, reviews: 128 },
        { name: "AirPro Max Buds", description: "True wireless earbuds with transparency mode", fullDescription: "Premium earbuds with adaptive EQ, transparency mode, and spatial audio for an immersive listening experience.", features: "Adaptive EQ\nTransparency mode\n24h battery\nSweat resistant\nAuto pause\nWireless charging", specs: '{"Driver": "10mm", "Bluetooth": "5.2", "Battery": "5h+19h", "Weight": "4.5g"}', price: 42000, image: "/img/images (4).jpeg", category: "Earphones", stock: 65, rating: 4.7, reviews: 95 },
        { name: "Sport Fit Earbuds", description: "Workout earbuds with secure fit and sweat resistance", fullDescription: "Designed for athletes with secure ear hooks, IPX7 waterproof rating, and powerful bass for motivation.", features: "IPX7 Waterproof\nEar hooks\nPowerful bass\n12h battery\nQuick charge\nVoice assistant", specs: '{"Driver": "12mm", "Water Rating": "IPX7", "Battery": "8h+4h", "Bluetooth": "5.0"}', price: 28000, image: "/img/images (9).jpeg", category: "Earphones", stock: 120, rating: 4.6, reviews: 210 },
        { name: "Studio Pro Earphones", description: "Wired earphones with studio-quality sound", fullDescription: "Professional-grade wired earphones with balanced armature drivers for accurate sound reproduction.", features: "Balanced armature\nDetachable cable\nNoise isolation\nMultiple tips\nCarrying case\nGold-plated jack", specs: '{"Driver": "Dual BA", "Impedance": "32Ω", "Cable": "1.2m", "Connector": "3.5mm"}', price: 18000, image: "/img/images (10).jpeg", category: "Earphones", stock: 90, rating: 4.5, reviews: 156 },
        { name: "Premium Noise Cancelling Headphones", description: "Over-ear headphones with industry-leading noise cancellation", fullDescription: "Immerse yourself in crystal-clear audio with these premium over-ear headphones featuring advanced ANC technology.", features: "Active ANC\n40mm drivers\n50-hour battery\nFoldable design\nMulti-device pairing\nComfort padding", specs: '{"Driver": "40mm", "Frequency": "20Hz-40kHz", "Battery": "50h", "Weight": "250g"}', price: 185000, image: "/img/Headphone 1.webp", category: "Headphones", stock: 35, rating: 4.9, reviews: 342 },
        { name: "Gaming Headset RGB", description: "7.1 surround sound gaming headset with RGB lighting", fullDescription: "Professional gaming headset with virtual 7.1 surround sound, noise-cancelling mic, and customizable RGB.", features: "7.1 Surround\nRGB lighting\nNoise-cancel mic\nMemory foam\n50mm drivers\nUSB connection", specs: '{"Driver": "50mm", "Surround": "7.1 Virtual", "Mic": "Detachable", "Cable": "2m"}', price: 95000, image: "/img/Bose-QuietComfort-Ultra-Headphones-black-1200x675.webp", category: "Headphones", stock: 55, rating: 4.7, reviews: 287 },
        { name: "Studio Monitor Headphones", description: "Professional studio headphones for mixing and mastering", fullDescription: "Flat frequency response headphones designed for audio professionals and music producers.", features: "Flat response\nOpen-back design\nVelour pads\nDetachable cable\nWide soundstage\nProfessional grade", specs: '{"Driver": "45mm", "Impedance": "250Ω", "Frequency": "5Hz-35kHz", "Cable": "3m"}', price: 145000, image: "/img/71E3rWecbKL._AC_SL1500_.jpg", category: "Headphones", stock: 28, rating: 4.8, reviews: 178 },
        { name: "Kids Safe Headphones", description: "Volume-limited headphones designed for children", fullDescription: "Colorful, durable headphones with 85dB volume limit to protect young ears during learning and entertainment.", features: "85dB limit\nDurable build\nAdjustable band\nSoft cushions\nTangle-free cable\nMultiple colors", specs: '{"Driver": "30mm", "Volume Limit": "85dB", "Cable": "1.2m", "Weight": "150g"}', price: 25000, image: "/img/images (11).jpeg", category: "Headphones", stock: 110, rating: 4.6, reviews: 425 },
        { name: "Amoled GPS Watch Pro", description: "Advanced fitness tracker with AMOLED display and GPS", fullDescription: "Premium smartwatch with vibrant AMOLED display, built-in GPS, comprehensive health tracking, and 7-day battery life.", features: "AMOLED display\nBuilt-in GPS\nHeart rate monitor\n100+ workout modes\n7-day battery\n5ATM waterproof", specs: '{"Display": "1.4-inch AMOLED", "Battery": "7 days", "GPS": "Built-in", "Water": "5ATM"}', price: 320000, image: "/img/Amoled GPS Watch.jpg", category: "Smart Watches", stock: 45, rating: 4.9, reviews: 567 },
        { name: "Fitness Tracker Band", description: "Slim fitness band with heart rate and sleep tracking", fullDescription: "Lightweight fitness tracker with continuous heart rate monitoring, sleep analysis, and 14-day battery life.", features: "Heart rate 24/7\nSleep tracking\n14-day battery\nWater resistant\nCall notifications\nMulti-sport modes", specs: '{"Display": "0.96-inch", "Battery": "14 days", "Sensors": "HR, SpO2", "Weight": "22g"}', price: 45000, image: "/img/images (7).jpeg", category: "Smart Watches", stock: 150, rating: 4.5, reviews: 892 },
        { name: "Luxury Smart Watch", description: "Premium smartwatch with sapphire glass and titanium case", fullDescription: "Luxury smartwatch combining traditional watch aesthetics with modern smart features and premium materials.", features: "Sapphire glass\nTitanium case\nECG sensor\nBlood oxygen\nAlways-on display\nPremium straps", specs: '{"Display": "1.5-inch OLED", "Material": "Titanium", "Battery": "5 days", "Water": "10ATM"}', price: 580000, image: "/img/images (8).jpeg", category: "Smart Watches", stock: 18, rating: 4.8, reviews: 234 },
        { name: "Kids GPS Watch", description: "GPS tracking watch for children with SOS button", fullDescription: "Safety-focused smartwatch for kids with real-time GPS tracking, SOS emergency button, and parental controls.", features: "GPS tracking\nSOS button\nTwo-way calls\nGeofencing\nWater resistant\nLong battery", specs: '{"Display": "1.3-inch", "GPS": "Real-time", "Battery": "3 days", "SIM": "Nano SIM"}', price: 75000, image: "/img/images.jpeg", category: "Smart Watches", stock: 85, rating: 4.7, reviews: 456 },
        { name: "Galaxy S24 Silicone Case", description: "Premium soft-touch silicone case with microfiber lining", fullDescription: "Protect your Galaxy S24 with this premium silicone case featuring soft-touch finish and precise cutouts.", features: "Soft-touch silicone\nMicrofiber lining\nShock absorption\nPrecise cutouts\nWireless charging\nEasy grip", specs: '{"Material": "Silicone", "Compatibility": "Galaxy S24", "Colors": "5 colors", "Weight": "30g"}', price: 22000, image: "/img/Blackweb-Soft-Touch-Silicone-Case-for-Galaxy-S10-Multiple-Colors_c4897984-871b-4e79-8d9d-992183e5b142_2.cb85c27d45cc6dc896eaf02e0980952b.jpeg", category: "Phone Cases", stock: 150, rating: 4.4, reviews: 678 },
        { name: "iPhone 15 Pro Clear Case", description: "Crystal clear case with military-grade drop protection", fullDescription: "Ultra-clear case that showcases your iPhone while providing military-grade protection against drops.", features: "Crystal clear\nMilitary grade\nYellow resistant\nRaised edges\nWireless charging\nSlim design", specs: '{"Material": "TPU", "Compatibility": "iPhone 15 Pro", "Drop": "3m", "Thickness": "1.2mm"}', price: 28000, image: "/img/Nebula X smartphone.jpg", category: "Phone Cases", stock: 200, rating: 4.6, reviews: 892 },
        { name: "Leather Wallet Case", description: "Premium leather case with card slots and stand", fullDescription: "Genuine leather flip case with multiple card slots, cash pocket, and built-in kickstand for hands-free viewing.", features: "Genuine leather\n3 card slots\nCash pocket\nKickstand\nMagnetic closure\nRFID protection", specs: '{"Material": "Leather", "Slots": "3 cards", "Universal": "4.7-6.7 inch", "RFID": "Yes"}', price: 35000, image: "/img/360_F_207154340_wLIJus4m3SBl5sAQmpqN3Um7REnUhskU.jpg", category: "Phone Cases", stock: 95, rating: 4.5, reviews: 345 },
        { name: "Rugged Armor Case", description: "Heavy-duty case with built-in screen protector", fullDescription: "Ultimate protection with dual-layer design, built-in screen protector, and port covers for dust protection.", features: "Dual layer\nScreen protector\nPort covers\nShock proof\nDust proof\nKickstand", specs: '{"Material": "PC+TPU", "Protection": "360°", "Drop": "5m", "IP Rating": "IP68"}', price: 32000, image: "/img/Annotation 2025-09-29 104718.png", category: "Phone Cases", stock: 120, rating: 4.7, reviews: 567 },
        { name: "Fast Charger Pro 65W", description: "65W USB-C fast charger with multiple ports", fullDescription: "Powerful GaN charger with 65W output, 3 ports for simultaneous charging, and compact foldable design.", features: "65W power\n3 USB ports\nGaN technology\nFoldable plug\nSmart charging\nCompact design", specs: '{"Power": "65W", "Ports": "2xUSB-C, 1xUSB-A", "Input": "100-240V", "Size": "6x6x3cm"}', price: 42000, image: "/img/Fast Charger.jpg", category: "Laptop Accessories", stock: 90, rating: 4.6, reviews: 445 },
        { name: "Wireless Charging Pad 15W", description: "Fast wireless charger with LED indicator", fullDescription: "Qi-certified 15W wireless charging pad with intelligent temperature control and foreign object detection.", features: "15W fast charge\nQi certified\nLED indicator\nNon-slip\nCase friendly\nSafe charging", specs: '{"Power": "15W", "Compatibility": "Qi devices", "Input": "USB-C", "Size": "10cm"}', price: 35000, image: "/img/Wireless Chager.jpg", category: "Laptop Accessories", stock: 70, rating: 4.5, reviews: 289 },
        { name: "USB-C Hub 7-in-1", description: "Multi-port USB-C hub with HDMI and card readers", fullDescription: "Expand your laptop connectivity with 7 ports including 4K HDMI, USB 3.0, SD/TF card readers, and PD charging.", features: "7 ports\n4K HDMI\nUSB 3.0\nSD/TF reader\n100W PD\nAluminum body", specs: '{"Ports": "7", "HDMI": "4K@60Hz", "USB": "3.0 5Gbps", "PD": "100W"}', price: 55000, image: "/img/PD 45W.jpg", category: "Laptop Accessories", stock: 65, rating: 4.7, reviews: 378 },
        { name: "Laptop Stand Aluminum", description: "Ergonomic laptop stand with adjustable height", fullDescription: "Premium aluminum laptop stand with 6 adjustable heights, ventilation design, and non-slip silicone pads.", features: "6 height levels\nAluminum alloy\nVentilation design\nNon-slip pads\nPortable\nUniversal fit", specs: '{"Material": "Aluminum", "Height": "6 levels", "Compatibility": "10-17 inch", "Weight": "280g"}', price: 38000, image: "/img/Showcase Alptop.webp", category: "Laptop Accessories", stock: 55, rating: 4.8, reviews: 512 },
        { name: "BoomBox Pro Speaker", description: "Powerful 40W stereo sound with 24-hour battery", fullDescription: "Portable Bluetooth speaker with 40W output, IPX7 waterproof rating, and impressive 24-hour playtime.", features: "40W stereo\n24h battery\nIPX7 waterproof\nBluetooth 5.0\nUSB-C charge\nBuilt-in mic", specs: '{"Power": "40W", "Battery": "24h", "Bluetooth": "5.0", "Water": "IPX7", "Weight": "850g"}', price: 155000, image: "/img/images (1).jpeg", category: "Jamboxes", stock: 40, rating: 4.7, reviews: 456 },
        { name: "Mini Portable Speaker", description: "Compact wireless speaker with 360° sound", fullDescription: "Ultra-portable speaker with 360-degree sound, 12-hour battery, and waterproof design for outdoor adventures.", features: "360° sound\n12h battery\nWaterproof\nCompact size\nCarabiner clip\nStereo pairing", specs: '{"Power": "5W", "Battery": "12h", "Size": "8cm", "Weight": "180g", "Water": "IPX6"}', price: 45000, image: "/img/images (3).jpeg", category: "Jamboxes", stock: 85, rating: 4.5, reviews: 678 },
        { name: "Party Speaker RGB", description: "High-power party speaker with LED lights", fullDescription: "Ultimate party speaker with 100W output, dynamic RGB lighting, karaoke function, and wireless mic support.", features: "100W power\nRGB lights\nKaraoke mode\nWireless mic\nUSB/SD input\nGuitar input", specs: '{"Power": "100W", "Battery": "8h", "Lights": "RGB", "Inputs": "USB, SD, AUX, Mic"}', price: 285000, image: "/img/5_in_1_dual_magsafe_charger_1.webp", category: "Jamboxes", stock: 25, rating: 4.8, reviews: 234 },
        { name: "NanoFlash 128GB USB 3.2", description: "Ultra-compact USB 3.2 flash drive with metal body", fullDescription: "Lightning-fast USB 3.2 flash drive with compact metal design, keyring hole, and 128GB storage capacity.", features: "USB 3.2\n128GB capacity\nMetal body\nKeyring hole\nPlug and play\nCompact design", specs: '{"Capacity": "128GB", "Interface": "USB 3.2", "Speed": "150MB/s read", "Material": "Metal"}', price: 15000, image: "/img/images (2).jpeg", category: "Flash Drives", stock: 200, rating: 4.5, reviews: 892 },
        { name: "Dual USB-C Flash Drive 256GB", description: "Dual connector flash drive for phones and computers", fullDescription: "Versatile flash drive with both USB-C and USB-A connectors for seamless file transfer between devices.", features: "Dual connector\n256GB storage\nUSB 3.1\nRotating design\nOTG support\nFast transfer", specs: '{"Capacity": "256GB", "Connectors": "USB-C + USB-A", "Speed": "200MB/s", "OTG": "Yes"}', price: 32000, image: "/img/images (5).jpeg", category: "Flash Drives", stock: 145, rating: 4.6, reviews: 567 },
        { name: "Encrypted USB Drive 512GB", description: "Hardware-encrypted flash drive with fingerprint lock", fullDescription: "Military-grade encrypted USB drive with fingerprint authentication and 512GB secure storage capacity.", features: "Fingerprint lock\n512GB secure\nHardware encryption\nWater resistant\nShock proof\nAES 256-bit", specs: '{"Capacity": "512GB", "Encryption": "AES 256", "Auth": "Fingerprint", "Speed": "180MB/s"}', price: 95000, image: "/img/images (6).jpeg", category: "Flash Drives", stock: 45, rating: 4.8, reviews: 234 },
        { name: "Elite Wireless Keyboard", description: "Mechanical keyboard with RGB backlight", fullDescription: "Professional mechanical keyboard with hot-swappable switches, RGB lighting, and wireless connectivity.", features: "Mechanical switches\nRGB backlight\nWireless + BT\n80h battery\nHot-swappable\nAluminum frame", specs: '{"Switches": "Mechanical", "Connectivity": "2.4GHz+BT", "Battery": "80h", "Layout": "104 keys"}', price: 135000, image: "/img/Keyboard.jpg", category: "Peripherals", stock: 65, rating: 4.7, reviews: 445 },
        { name: "Gaming Mouse Pro 25K DPI", description: "Ergonomic wireless gaming mouse with 25K sensor", fullDescription: "High-performance gaming mouse with 25K DPI sensor, 12 programmable buttons, and 70-hour battery life.", features: "25K DPI\n12 buttons\nRGB lighting\nWireless+wired\n70h battery\nErgonomic", specs: '{"DPI": "25,000", "Buttons": "12", "Battery": "70h", "Connectivity": "2.4GHz+BT"}', price: 68000, image: "/img/Showcase 2.png", category: "Peripherals", stock: 75, rating: 4.8, reviews: 678 },
        { name: "4K Webcam Pro", description: "4K webcam with AI background removal", fullDescription: "Professional 4K webcam with AI-powered background removal, auto-focus, and dual microphone array.", features: "4K resolution\nAI background\nAuto-focus\nDual mics\nLow light\nPrivacy shutter", specs: '{"Resolution": "4K 30fps", "FOV": "90°", "Mic": "Dual array", "Mount": "Universal"}', price: 165000, image: "/img/Showcase 3.png", category: "Peripherals", stock: 45, rating: 4.6, reviews: 289 },
        { name: "RGB Mouse Pad XXL", description: "Extended gaming mouse pad with RGB lighting", fullDescription: "Extra-large RGB mouse pad with smooth surface, non-slip rubber base, and customizable lighting effects.", features: "XXL size\nRGB lighting\nSmooth surface\nNon-slip base\nWater resistant\nUSB powered", specs: '{"Size": "900x400mm", "Thickness": "4mm", "RGB": "16.8M colors", "Cable": "1.8m"}', price: 35000, image: "/img/Showcase Carousel img.jpg", category: "Peripherals", stock: 95, rating: 4.5, reviews: 567 }
    ]

    for (const product of products) {
        await prisma.product.create({ data: product })
    }

    console.log(`✅ Seeded ${products.length} products with LOCAL images from /img/ folder!`)
}

main()
    .catch((e) => {
        console.error('❌ Error:', e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
